#!/bin/bash

die() {
	echo "$0: $*" >&2
	exit 1
}

log() {
	echo "$*" >&2
}

output() {
	echo -n "$*"
}

## find the workspace root directory and output to stdout
wksp_rootdir() {
	detect_rootdir
	output "$WORKSPACER_ROOT"
}

#
# detect workspace root directory (exported to WORKSPACE_ROOT)
#
detect_rootdir() {
	local CWD=`pwd`
	if [ -f "$CWD/cf/workspace.cf" ]; then
		export WORKSPACE_ROOT="$CWD"
		return 0
	fi

	while [ "$CWD" != "" ] && [ "$CWD" != "/" ]; do
		if [ -f "$CWD/cf/workspace.cf" ]; then
			export WORKSPACE_ROOT="$CWD"
			return
		fi
		CWD=`dirname "$CWD"`
	done
	die "cant find rootdir with workspace.cf"
}

#
# list packages
# requires $WORKSPACE_ROOT to be set
#
wksp_packages() {
	for i in $WORKSPACE_ROOT/cf/packages/*.cf ; do
		if [ -f "$i" ]; then
			bn=`basename "$i"`
			echo "${bn%%.cf}"
		fi
	done
}

#
# generate global configuration (as shellscript piece)
# requires $WORKSPACE_ROOT to be set
#
wksp_generate_global_config_1() {
	detect_rootdir
	echo "declare -A WORKSPACE_CONFIG"
	cat $WORKSPACE_ROOT/cf/workspace.cf | sed -e 's~#.*~~; s~^[ \t].*~~; s~[ \t]*$~~;' | grep -vE "^$" | \
		while read line ; do
			key=`echo "$line" | sed -e 's~:.*~~'`
			value="${line##$key:}"
			value="${value#"${value%%[![:space:]]*}"}"
			value="${value//\{WORKSPACE_ROOT\}/$WORKSPACE_ROOT}"
			echo "export WORKSPACE_CONFIG[\"${key}\"]=\"$value\""
		done
	for i in LANG LANGUAGE LC_PAPER LC_ADDRESS LC_MONETARY LC_NUMERIC LC_ALL \
                 LC_TELEPHONE LC_MESSAGES LC_IDENTIFICATION LC_COLLATE \
                 LC_MEASUREMENT LC_CTYPE LC_TIME LC_NAME ; do
		echo "unset $i"
	done
}

wksp_generate_global_config() {
	eval `wksp_generate_global_config_1`
	wksp_generate_global_config_1
	for d in ${WORKSPACE_CONFIG["dpkg.distros"]} ; do
		cf="$WORKSPACE_ROOT/cf/dist/$d.cf"
		if [ -f "$cf" ]; then
			cat $cf | sed -e 's~#.*~~; s~^[ \t].*~~; s~[ \t]*$~~;' | grep -vE "^$" | \
				while read line ; do
					key=`echo "$line" | sed -e 's~:.*~~'`
					value="${line##$key:}"
					value="${value#"${value%%[![:space:]]*}"}"
					value="${value//\{WORKSPACE_ROOT\}/$WORKSPACE_ROOT}"
					echo "export WORKSPACE_CONFIG[\"dpkg.dist.$d.${key}\"]=\"$value\""
				done
		fi
	done
}

#
# generate configuration (as shellscript piece) for specific target/arch
#
# $1: target distro (eg. precise, squeeze, ...)
# $2: target architecture
#
wksp_generate_target_config() {
	local TARGET_DIST="$1"
	local TARGET_ARCH="$2"

	if [ ! "$TARGET_ARCH" ]; then
		local TARGET_ARCH=`dpkg --print-architecture`
	fi

	local TARGET_IDENT="${TARGET_DIST}-${TARGET_ARCH}"

	detect_rootdir
	eval `wksp_generate_global_config`
	echo "declare -A TARGET_CONFIG"
	for i in LANG LANGUAGE LC_PAPER LC_ADDRESS LC_MONETARY LC_NUMERIC LC_ALL \
                 LC_TELEPHONE LC_MESSAGES LC_IDENTIFICATION LC_COLLATE \
                 LC_MEASUREMENT LC_CTYPE LC_TIME LC_NAME ; do
		echo "unset $i"
	done

	local BASE_COW="${WORKSPACE_CONFIG["dpkg.target.cow"]//\{DISTRO\}/$TARGET_IDENT}"
	local BASE_TGZ="${WORKSPACE_CONFIG["dpkg.target.tgz"]//\{DISTRO\}/$TARGET_IDENT}"
	local COMPONENTS="${WORKSPACE_CONFIG["dpkg.dist.$TARGET_DIST.components"]}"
	local MIRROR="${WORKSPACE_CONFIG["dpkg.dist.$TARGET_DIST.mirror"]}"
	local OTHERMIRROR="${WORKSPACE_CONFIG["dpkg.dist.$TARGET_DIST.othermirror"]}"
	local KEYRING="${WORKSPACE_CONFIG["dpkg.dist.$TARGET_DIST.keyring"]}"
	local PBUILDERRC="$WORKSPACE_ROOT/tmp/pbuilder-$TARGET_IDENT.rc"
	local DISRO="${WORKSPACE_CONFIG["dpkg.dist.$TARGET_DIST.distro"]}"
	local APTREPO="${WORKSPACE_CONFIG["apt.target.repository"]}"
	local TARGET_COMPONENT="${WORKSPACE_CONFIG["dpkg.dist.$TARGET_DIST.target-component"]}"

	local walk
	for walk in 0 1 2 3 4 5 6 7 8 9 ; do
	    local tmp="${WORKSPACE_CONFIG["dpkg.dist.$TARGET_DIST.othermirror.$walk"]}"
            [ "$tmp" ] && OTHERMIRROR="$OTHERMIRROR|$tmp"
	done

	## add our local repo
#	OTHERMIRROR="$OTHERMIRROR|deb [trusted=yes] file:///$APTREPO $DISTRO"
	OTHERMIRROR="$OTHERMIRROR|deb file:///$APTREPO $DISTRO"

	if [ ! "$DISTRO" ]; then
		local DISTRO="$TARGET_DIST"
	fi

	echo "export TARGET_CONFIG[name]=\"$TARGET_DIST\""
	echo "export TARGET_CONFIG[dist]=\"$TARGET_DIST\""
	echo "export TARGET_CONFIG[ident]=\"$TARGET_IDENT\""
	echo "export TARGET_CONFIG[type]=\"dpkg\""
	echo "export TARGET_CONFIG[base.tgz]=\"$BASE_TGZ\""
	echo "export TARGET_CONFIG[base.cow]=\"$BASE_COW\""
	echo "export TARGET_CONFIG[components]=\"$COMPONENTS\""
	echo "export TARGET_CONFIG[mirror]=\"$MIRROR\""
	echo "export TARGET_CONFIG[othermirror]=\"$OTHERMIRROR\""
	echo "export TARGET_CONFIG[keyring]=\"$KEYRING\""
	echo "export TARGET_CONFIG[pbuilderrc]=\"$PBUILDERRC\""
	echo "export TARGET_CONFIG[distro]=\"$DISTRO\""
	echo "export TARGET_CONFIG[architecture]=\"$TARGET_ARCH\""
	echo "export TARGET_CONFIG[aptrepo]=\"$APTREPO\""
	echo "export TARGET_CONFIG[hookdir]=\"$WORKSPACE_ROOT/scripts/hooks\""
	echo "export TARGET_CONFIG[target-component]=\"$TARGET_COMPONENT\""
}

#
# generate target-specific pbuilderrc
#
# $1: target dist name (eg. precise, squeeze, ...)
# $2: target architecture
#
wksp_generate_pbuilderrc() {
	local TARGET_DIST="$1"
	local TARGET_ARCH="$2"

	[ "$TARGET_DIST" ] || die "wksp_generate_pbuilderrc: missing target dist"

	eval `wksp_generate_target_config $TARGET_DIST $TARGET_ARCH`
	mkdir -p `dirname "${TARGET_CONFIG[pbuilderrc]}"`
	(
		echo "export BASETGZ=\"${TARGET_CONFIG[base.tgz]}\""
		echo "export BASEPATH=\"${TARGET_CONFIG[base.cow]}\""
		echo "export BUILDPLACE=\"${TARGET_CONFIG[base.cow]}\""
		echo "export COMPONENTS=\"${TARGET_CONFIG[components]}\""
		echo "export MIRRORSITE=\"${TARGET_CONFIG[mirror]}\""
		echo "export OTHERMIRROR=\"${TARGET_CONFIG[othermirror]}\""
		echo "export ARCHITECTURE=\"${TARGET_CONFIG[architecture]}\""
		echo "export DISTRIBUTION=\"${TARGET_CONFIG[distro]}\""
		echo "export DEBOOTSTRAPOPTS=( '--variant=buildd' '--keyring' '${TARGET_CONFIG["keyring"]}' )"
		echo "export HOOKDIR=\"${TARGET_CONFIG[hookdir]}\""
		echo "export BINDMOUNTS=\"${TARGET_CONFIG[aptrepo]}\""
		echo "export EXTRAPACKAGES=\"${TARGET_CONFIG[extrapackages]}\""
	) > "${TARGET_CONFIG[pbuilderrc]}"
}

wksp_load_global_config () {
	detect_rootdir
	eval `wksp_generate_global_config`
	export WORKSPACE_CONFIG
}

wksp_generate_package_config() {
	local package="$1"
	export PACKAGE_NAME="\"$package\""
	echo "declare -A PACKAGE_CONFIG"
	echo "export PACKAGE_CONFIG[\"local_workdir\"]=\"$WORKSPACE_ROOT/pkg/$package.git\""
	echo "export PACKAGE_CONFIG[\"package\"]=\"$package\""
	cat $WORKSPACE_ROOT/cf/packages/$package.cf | sed -e 's~#.*~~; s~^[ \t].*~~; s~[ \t]*$~~;' | grep -vE "^$" | \
	(
		while read line ; do
			key=`echo "$line" | sed -e 's~:.*~~'`
			value="${line##$key:}"
			value="${value#"${value%%[![:space:]]*}"}"
			value="${value//\{WORKSPACE_ROOT\}/$WORKSPACE_ROOT}"
			variable=`echo "$key" | tr '.' '_' | tr '-' '_'`
			echo "export PACKAGE_CONFIG[\"$key\"]=\"$value\""
		done
	)
}

#
# add remote git repository to project
#
# $1: workdir
# $2: remote name
# $3: repo url
#
wks_project_add_remote_git() {
	(
		local WORKDIR="$1"
		local REMOTE_NAME="$2"
		local UPSTREAM_REPO="$3"
		cd "$WORKDIR" || return 1
		git config remote.$REMOTE_NAME.url "$UPSTREAM_REPO"
		git config remote.$REMOTE_NAME.fetch "+refs/heads/*:refs/remotes/$REMOTE_NAME/*"
		git remote update $REMOTE_NAME
	)
}

#
# add remote bzr repository to project
#
# $1: workdir
# $2: remote name
# $3: repo url
#
wks_project_add_remote_bzr() {
	(
		local WORKDIR="$1"
		local REMOTE_NAME="$2"
		local UPSTREAM_REPO="$3"
		cd "$WORKDIR" || return 1
		UPSTREAM_REPO="${UPSTREAM_REPO##bzr::}"
		git bzr import "${UPSTREAM_REPO}"
		for i in `git branch | grep "bzr/"`; do git bzr sync "$i" ; done
	)
}

#
# add (external) upstream repo to our local package clone
#
# $1: package workdir
# $2: remote name
# $3: upstream repo location
#
wks_project_add_remote() {
	local WORKDIR="$1"
	local REMOTE_NAME="$2"
	local UPSTREAM_REPO="$3"

	if [ "$UPSTREAM_REPO" == "" ]; then
		return 0
	fi

	case "$UPSTREAM_REPO" in
		git://*)
			wks_project_add_remote_git "$WORKDIR" "$REMOTE_NAME" "$UPSTREAM_REPO"
		;;
		GIT:https://*)
			wks_project_add_remote_git "$WORKDIR" "$REMOTE_NAME" "$UPSTREAM_REPO"
		;;
		bzr::*)
			wks_project_add_remote_bzr "$WORKDIR" "$REMOTE_NAME" "$UPSTREAM_REPO"
		;;
		*)
			wks_project_add_remote_git "$WORKDIR" "$REMOTE_NAME" "$UPSTREAM_REPO"
		;;
	esac
}

wksp_sync_package() {
	local package="$1"

	eval `wksp_generate_global_config`
	eval `wksp_generate_package_config "${package}"`

	local repo=${PACKAGE_CONFIG["local_workdir"]}

	echo "Synchronizing package: ${package}"

	git init ${PACKAGE_CONFIG["local_workdir"]} 2>&1 | grep -vE "^Reinitialized existing Git repository in"
	ln -sf scripts/build.sh ${WORKSPACE_ROOT}/build-${package}

	for remote in ${WORKSPACE_CONFIG["scm.remotes"]} ; do
		local project=${PACKAGE_CONFIG["remote.${remote}.project"]}
		local url=${WORKSPACE_CONFIG["scm.remote.${remote}.url"]}
		if [ "$project" ]; then
			local url="${url//\{PROJECT\}/${project}}"
			wks_project_add_remote "${PACKAGE_CONFIG["local_workdir"]}" "${remote}" "${url}"
		fi
	done
}

wksp_sync_packages() {
	for pkg in `wksp_packages` ; do
		wksp_sync_package "$pkg"
	done
}

wksp_help_line() {
	local cmd="$1"
	shift
	local par="$1"
	shift
	printf "  %-35s %s" "$cmd $par" "$*"
	echo
}

wksp_help() {
	echo "usage: wksp <command>"
	echo ""
	echo "commands:"
	echo ""
	wksp_help_line "sync"		""		"synchronize workspace with remotes"
	wksp_help_line "build-dpkg"	"<package>"	"build debian package from current branch using pbuilder"
	wksp_help_line "prepare-dpkg"	"<distro>"	"prepare pbuilder environment for given distro"
	wksp_help_line "update-dpkg"	"<distro>"	"update pbuilder environment for given distro"
	wksp_help_line "update-aptrepo"	""		"update the local apt repositories"
	wksp_help_line "clean-aptrepo"	""		"clean local apt repository"
	wksp_help_line "help"		""		"this help page"
	echo ""
	exit
}

git_get_current_branch() {
	( cd "$1" && git branch | grep '\*' | sed -e 's~[\* ]*~~' )
}

# $1: target distribution
# $2: target architecture
wksp_dpkg_prepare_pbuilder() {

	eval `wksp_generate_global_config`

	local TARGET_DIST="$1"
	local TARGET_ARCH="$2"

	if [ ! "$TARGET_DIST" ]; then
		die "$0: missing target distro name"
	fi

	eval `wksp_generate_target_config $TARGET_DIST $TARGET_ARCH`
	wksp_generate_pbuilderrc $TARGET_DIST $TARGET_ARCH

	if [ "$TARGET_ARCH" ]; then
		TARGET_IDENT="${TARGET_DIST}-${TARGET_ARCH}"
	else
		TARGET_IDENT="${TARGET_DIST}"
	fi

	if [ -d "${TARGET_CONFIG[base.cow]}" ]; then
		log "[$TARGET_DIST] COW image already set up: ${TARGET_CONFIG["base.cow"]}"
		return 0
	fi

	log "[$TARGET_DIST] need to create cow image: ${TARGET_CONFIG["base.cow"]}"

	sudo cowbuilder --create --configfile "${TARGET_CONFIG["pbuilderrc"]}"

	echo "force-unsafe-io" > .tmp_aptcf
	sudo mkdir -p "${TARGET_CONFIG["base.cow"]}/etc/dpkg/dpkg.cfg.d"
	sudo cp .tmp_aptcf "${TARGET_CONFIG["base.cow"]}/etc/dpkg/dpkg.cfg.d/02apt-speedup"
	rm -f .tmp_aptcf
}

wksp_build_dpkg() {
	local PACKAGE="$1"
	[ "$PACKAGE" ] || die "missing package name"
	[ -f "$WORKSPACE_ROOT/cf/packages/$PACKAGE.cf" ] || die "unknown package: $PACKAGE"
	eval `wksp_generate_global_config`
	eval `wksp_generate_package_config "${PACKAGE}"`
	export WORKSPACE_CONFIG
	export PACKAGE_CONFIG
	local CURRENT_BRANCH=`git_get_current_branch ${PACKAGE_CONFIG["local_workdir"]}`
	for d in ${WORKSPACE_CONFIG["dpkg.distros"]} ; do
		if [[ "$CURRENT_BRANCH" == $d/* ]]; then
			local TARGET_DIST="$d"
			local TARGET_IDENT="$d"
		fi
		for a in ${WORKSPACE_CONFIG["dpkg.architectures"]} ; do
			if [[ "$CURRENT_BRANCH" == $d-$a/* ]]; then
				local TARGET_DIST="$d"
				local TARGET_ARCH="$a"
				local TARGET_IDENT="$d-$a"
			fi
		done
	done
	[ "$TARGET_DIST" ] || die "cant detect target distro. maybe you need to checkout the right branch"
	[ "$TARGET_ARCH" ] || export TARGET_ARCH=`dpkg --print-architecture`

	wksp_dpkg_prepare_pbuilder "$TARGET_DIST" "$TARGET_ARCH"
	eval `wksp_generate_target_config "$TARGET_DIST" "$TARGET_ARCH"`

	local EXPORT_DIR="${WORKSPACE_CONFIG["pbuilder.tempdir"]}/output/${PACKAGE}/${TARGET_DIST_IDENT}"
	local ORIG_TARBALL_PREFIX="${WORKSPACE_CONFIG["pbuilder.tempdir"]}/tarballs/${PACKAGE}/${TARGET_DIST_IDENT}"
	local BUILDPLACE="${WORKSPACE_CONFIG["dpkg.target.buildplace"]}"
	BUILDPLACE="${BUILDPLACE//\{DISTRO\}/$TARGET_IDENT}"
	BUILDPLACE="${BUILDPLACE//\{PACKAGE\}/$PACKAGE}"

	rm -Rf ${EXPORT_DIR}
	mkdir -p ${EXPORT_DIR}

	export GIT_PBUILDER_OPTIONS="--hookdir ${TARGET_CONFIG[hookdir]} --bindmounts ${TARGET_CONFIG[aptrepo]}"
	export APT_REPO="${TARGET_CONFIG[aptrepo]}"
	export APT_DIST="${TARGET_CONFIG[dist]}"
	export APT_COMPONENTS="${TARGET_CONFIG[components]}"
	export GIT_PBUILDER_AUTOCONF=1

	echo "BUILDPLACE=$BUILDPLACE"

	( cd "${PACKAGE_CONFIG["local_workdir"]}" && git-buildpackage	\
		--git-verbose						\
		--git-pbuilder						\
		--git-dist=${TARGET_IDENT}				\
		--git-tarball-dir=${ORIG_TARBALL_PREFIX}/${PACKAGE}	\
		--git-export-dir=${EXPORT_DIR}				\
		--git-debian-branch=${CURRENT_BRANCH}			\
		--git-upstream-branch=${CURRENT_BRANCH}			\
		--git-upstream-tree=branch				\
		--git-no-pristine-tar					\
		--git-no-create-orig					\
		--git-hooks						\
		--git-compression=1					\
		--git-pbuilder-options="--buildplace ${BUILDPLACE} --preserve-buildplace"
		) || return 1

	for deb in `find ${EXPORT_DIR} -name "*.deb"` ; do
		echo "Found deb file: $deb"
		local pooldir="${APT_REPO}/pool/dists/${TARGET_DIST}/${TARGET_CONFIG[target-component]}/${PACKAGE}"
		mkdir -p $pooldir
		echo "Copying to pooldir: $pooldir"
		cp $deb $pooldir
	done

	wksp_aptrepo_update
}

wksp_aptrepo_update() {
	eval `wksp_generate_global_config`
	local ARCHIVE_ROOT="${WORKSPACE_CONFIG["apt.target.repository"]}"
	local ARCHIVE_CONF="${ARCHIVE_ROOT}/conf/apt-ftparchive.conf"
	local ARCHIVE_CONF_TMPL="$WORKSPACE_ROOT/cf/apt/apt-ftparchive.conf.tmpl"
	local ARCHIVE_PART_TMPL="$WORKSPACE_ROOT/cf/apt/apt-ftparchive.part.tmpl"
	local RELEASE_CONF_TMPL="$WORKSPACE_ROOT/cf/apt/apt-distro-release.conf.tmpl"
	local DISTS="${WORKSPACE_CONFIG["dpkg.distros"]}"
	local ARCHITECTURES="${WORKSPACE_CONFIG["dpkg.architectures"]}"

	mkdir -p ${ARCHIVE_ROOT}

	rm -Rf ${ARCHIVE_ROOT}/cache

	## export our local sign key
	gpg --export -a > ${ARCHIVE_ROOT}/local-repo.pub

	local CLEAN_FILES="
		Release
		Release.gpg
		Release.gpg.gz
		Release.gpg.bz2
		Release.gz
		Release.bz2
		Packages
		Packages.gz
		Packages.bz2
	"

	for i in $CLEAN_FILES ; do find ${ARCHIVE_ROOT} -name "$i" -delete ; done

	mkdir -p ${ARCHIVE_ROOT}/cache ${ARCHIVE_ROOT}/conf

	cat $ARCHIVE_CONF_TMPL \
		> ${ARCHIVE_CONF}

	for d in ${DISTS} ; do

		local CODENAME="$d"
		local SECTIONS="${WORKSPACE_CONFIG["dpkg.dist.$d.sections"]}"
		local COMPONENTS="${WORKSPACE_CONFIG["dpkg.dist.${d}.components"]}"
		local LABEL="${WORKSPACE_CONFIG["dpkg.dist.${d}.label"]}"
		local DESCRIPTION="${WORKSPACE_CONFIG["dpkg.dist.${d}.description"]}"

		cat $ARCHIVE_PART_TMPL \
			| sed -e "s~@SECTIONS@~${COMPONENTS}~; s~@ARCHITECTURES@~${ARCHITECTURES}~; s~@DISTRO@~$d~;" \
			>> ${ARCHIVE_CONF}
		mkdir -p ${ARCHIVE_ROOT}/dists/$d

		for s in ${COMPONENTS} ; do
			mkdir -p ${ARCHIVE_ROOT}/pool/dists/$d/$s
			for a in ${ARCHITECTURES} ; do
				mkdir -p ${ARCHIVE_ROOT}/dists/$d/$s/binary-$a/
				touch ${ARCHIVE_ROOT}/dists/$d/$s/binary-$a/Packages
			done
		done

		cat $RELEASE_CONF_TMPL \
			| sed -e "s~@SECTIONS@~${SECTIONS}~g"						\
			| sed -e "s~@ARCHITECTURES@~${ARCHITECTURES}~g"					\
			| sed -e "s~@CODENAME@~${CODENAME}~g"						\
			| sed -e "s~@DISTRO@~${d}~g"							\
			| sed -e "s~@LABEL@~${LABEL}~g"		\
			| sed -e "s~@COMPONENTS@~${COMPONENTS}~g"					\
			| sed -e "s~@DESCRIPTION@~${DESCRIPTION}~g"	\
			> ${ARCHIVE_ROOT}/conf/apt-$d-release.conf
	done

	(cd ${ARCHIVE_ROOT} && apt-ftparchive generate ${ARCHIVE_CONF} 2>&1 )

	for d in ${DISTS}; do
		DIST_ROOT=${ARCHIVE_ROOT}/dists/$d
		(cd ${ARCHIVE_ROOT} && apt-ftparchive -c ${ARCHIVE_ROOT}/conf/apt-$d-release.conf release ${DIST_ROOT} > ${DIST_ROOT}/Release.tmp )
		mv ${DIST_ROOT}/Release.tmp ${DIST_ROOT}/Release
		gpg -abs -o ${DIST_ROOT}/Release.gpg ${DIST_ROOT}/Release
	done

	(
		echo -n "Experimental repo. Created at: "
		hostname --fqdn
		date
	) > ${ARCHIVE_ROOT}/INFO
}

wksp_aptrepo_clean() {
	eval `wksp_generate_global_config`
	local ARCHIVE_ROOT="${WORKSPACE_CONFIG["apt.target.repository"]}"
	local ARCHIVE_CONF="${ARCHIVE_ROOT}/conf/apt-ftparchive.conf"
	local DISTS="${WORKSPACE_CONFIG["dpkg.distros"]}"
	local ARCHITECTURES="${WORKSPACE_CONFIG["dpkg.architectures"]}"

	local ARCHIVE_ROOT="${WORKSPACE_CONFIG["apt.target.repository"]}"
	[ "$ARCHIVE_ROOT" ] || die "$0: missing config apt.target.repository"

	rm -Rf	\
		$ARCHIVE_ROOT/cache			\
		$ARCHIVE_ROOT/conf/apt-ftparchive.conf	\
		$ARCHIVE_ROOT/INFO

	for d in $DISTS ; do
		rm -f $ARCHIVE_ROOT/conf/apt-$d-release.conf
	done

	if [ -d "$ARCHIVE_ROOT/dists" ]; then
		find "$ARCHIVE_ROOT/dists" -name "Release" -delete
		find "$ARCHIVE_ROOT/dists" -name "Release.gpg" -delete
		find "$ARCHIVE_ROOT/dists" -name "Packages" -delete
		find "$ARCHIVE_ROOT/dists" -name "Packages.gz" -delete
		find "$ARCHIVE_ROOT/dists" -name "Packages.bz2" -delete
		for a in all $ARCHITECTURES ; do
			find $ARCHIVE_ROOT/dists -name "Contents-$a.gz" -delete
		done
	fi

	if [ -d "$ARCHIVE_ROOT/pool" ]; then
		find "$ARCHIVE_ROOT/pool" -name "*.deb" -delete
	fi

	for i in 1 2 3 4 5 6 7 ; do
		find $ARCHIVE_ROOT -type d -exec "rmdir" "{}" ";" 2>/dev/null
	done
}

[ "$1" ] || wksp_help

wksp_load_global_config

unset LC_CTYPE
unset LANGUAGE
unset LC_ALL
unset LC_TIME
unset LC_MONETARY
unset LC_COLLATE
unset LC_ADDRESS
unset LC_TELEPHONE
unset LC_MESSAGES
unset LC_NAME
unset LC_MEASUREMENT
unset LC_IDENTIFICATION
unset LC_NUMERIC
unset LC_PAPER
unset LANG

while [ "$1" ]; do
	opt="$1"
	shift

	case "$opt" in
		"sync"|"--sync")
			wksp_sync_packages
			exit 0
		;;
		"build-dpkg"|"--build-dpkg")
			wksp_build_dpkg "$*"
			exit 0
		;;
		"prepare-dpkg"|"--prepare-dpkg")
			wksp_dpkg_prepare_pbuilder "$*"
			exit 0
		;;
		"update-aptrepo"|"--update-aptrepo")
			wksp_aptrepo_update "$*"
			exit 0
		;;
		"clean-aptrepo"|"--clean-aptrepo")
			wksp_aptrepo_clean "$*"
			exit 0
		;;
		"target-config")
			wksp_generate_target_config "$@"
			exit 0
		;;
		"pbuilderrc")
			wksp_generate_pbuilderrc "$@"
			exit 0
		;;
		"global-config")
			wksp_generate_global_config
		;;
		*)
			wksp_help
			exit 0
		;;
	esac
done
