#!/bin/bash
#
# this hook enables our local repo inside the build chroot
#

APT_REPO_URL="file://$APT_REPO"

for i in repo.pub local-repo.pub ; do
	if [ -f "$APT_REPO/$i" ]; then
		echo "Enabling repo key: $i"
		apt-key add "$APT_REPO/$i"
	fi
done

echo "deb $APT_REPO_URL $APT_DIST $APT_COMPONENTS" >> /etc/apt/sources.list

apt-get update

exit 0
